name: AzureLoginSample
on: 
 push:
 schedule:
  - cron: "*/30 * * * *"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        run: |
         az login --service-principal -u "a42814c2-34d3-4af6-add8-1f06178c8332" -p "7YYDwpD.T7m97Y7LIXN-2_dlVr2xERo1N5" --tenant "bd5c6713-7399-4b31-be79-78f2d078e543"
         az group list
        shell: bash
