name: AzureLoginSample
on: 
  pull_request:
    types:
      - closed
  schedule:
   - cron: "*/30 * * * *"


jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        run: |
         az login --service-principal -u '${{ secrets.APPID}}' -p '${{ secrets.PASSWORD }}' --tenant '${{ secrets.TENANT}}'
         az group list -o table
        shell: bash
