name: AzureLoginSample
on: 
 push:
 schedule:
  - cron: "*/30 * * * *"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        run: |
         az login --service-principal -u '${{ secrets.APPID}}' -p '${{ secrets.PASSWORD }}' --tenant '${{ secrets.TENANT}}'
         az group list -o table
        shell: bash
