name: AzureLoginSample
on: 
 push:
 schedule:
  - cron: "*/30 * * * *"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log in with Azure
        run: |
         az login --service-principal -u '${{ secrets.AZURE_CREDENTIALS.appId }}' -p '${{ secrets.AZURE_CREDENTIALS.passowrd }}' --tenant '${{ secrets.AZURE_CREDENTIALS.tenant }}'
         az group list
        shell: bash
